Repository selab-hs/selab-core-api, pull requests merged in 2022-01, with the labels that each got.

#3 ✨ [Feature/common-2] Swagger Config 등록
  src/main/java/kr/ac/hs/selab/config/SwaggerConfig.java
Labels: feature

#5 ✨ [Feature/common-4] 공통 도메인 구현 진행
  LICENSE
  src/main/java/kr/ac/hs/selab/SelabApplication.java
  src/main/java/kr/ac/hs/selab/common/config/JpaConfig.java
  src/main/java/kr/ac/hs/selab/common/config/PropertiesConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SwaggerConfig.java
  src/main/java/kr/ac/hs/selab/common/domain/BaseEntity.java
  src/main/java/kr/ac/hs/selab/common/dto/ResponseDto.java
  src/main/java/kr/ac/hs/selab/common/dto/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/properties/SwaggerProperties.java
  src/main/java/kr/ac/hs/selab/config/SwaggerConfig.java
  src/main/java/kr/ac/hs/selab/error/BusinessException.java
  src/main/java/kr/ac/hs/selab/error/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/error/dto/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/error/dto/ErrorResponseDto.java
  src/main/resources/application-swagger.properties
  src/main/resources/application.properties
Labels: feature

#7 ✨ [Feature/member-6] 회원 도메인 기본 인프라 구성
  src/main/java/kr/ac/hs/selab/common/dto/ResponseDto.java
  src/main/java/kr/ac/hs/selab/common/dto/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthController.java
  src/main/java/kr/ac/hs/selab/common/utils/ValidationUtils.java
  src/main/java/kr/ac/hs/selab/error/dto/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/error/dto/ErrorResponseDto.java
  src/main/java/kr/ac/hs/selab/error/exception/BusinessException.java
  src/main/java/kr/ac/hs/selab/error/exception/common/InvalidArgumentException.java
  src/main/java/kr/ac/hs/selab/error/handler/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/converter/MemberConverter.java
  src/main/java/kr/ac/hs/selab/member/domain/Member.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Avatar.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Email.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Name.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Nickname.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Password.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Role.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/StudentId.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Terms.java
  src/main/java/kr/ac/hs/selab/member/dto/bundle/CreateMemberBundle.java
  src/main/java/kr/ac/hs/selab/member/dto/request/CreateMemberRequest.java
  src/main/java/kr/ac/hs/selab/member/dto/response/CreateMemberResponse.java
  src/main/java/kr/ac/hs/selab/member/infrastructure/MemberRepository.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
Labels: feature

#16 ♻️ [Refactor/member-15] 기본적인 리펙토링
  src/main/java/kr/ac/hs/selab/common/dto/ResponseDto.java
  src/main/java/kr/ac/hs/selab/common/dto/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthAbstractController.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthController.java
  src/main/java/kr/ac/hs/selab/common/utils/ValidationUtils.java
  src/main/java/kr/ac/hs/selab/error/dto/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/error/dto/ErrorResponseDto.java
  src/main/java/kr/ac/hs/selab/error/exception/BusinessException.java
  src/main/java/kr/ac/hs/selab/error/exception/common/DuplicationException.java
  src/main/java/kr/ac/hs/selab/error/handler/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/converter/MemberConverter.java
  src/main/java/kr/ac/hs/selab/member/domain/Member.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Avatar.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Email.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Name.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Nickname.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Password.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/StudentId.java
  src/main/java/kr/ac/hs/selab/member/dto/response/CreateMemberResponse.java
  src/main/java/kr/ac/hs/selab/member/infrastructure/MemberRepository.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberAbstractController.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
Labels: refactor

#21 ✨ [Refactor/auth-13] 인증 및 인가 리펙토링
  src/main/java/kr/ac/hs/selab/auth/converter/AuthConverter.java
  src/main/java/kr/ac/hs/selab/auth/dto/response/LoginResponse.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/auth/presentation/AuthController.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Role.java
Labels: refactor

#23 ♻️ [Refactor/common-19] Response Template 리펙토링
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/error/handler/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorTemplate.java
Labels: refactor

#25 ♻️ [Refactor/common-18] Swagger 수정
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SwaggerConfig.java
  src/main/java/kr/ac/hs/selab/common/properties/SwaggerProperties.java
  src/main/resources/application-swagger.properties
  src/main/resources/application.properties
Labels: refactor

#27 🐛 [Fix/common-26] Swagger 상세정보 추가
  src/main/java/kr/ac/hs/selab/auth/dto/request/LoginRequest.java
  src/main/java/kr/ac/hs/selab/auth/dto/response/LoginResponse.java
  src/main/java/kr/ac/hs/selab/auth/presentation/AuthSwaggerController.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthSwaggerController.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorTemplate.java
  src/main/java/kr/ac/hs/selab/member/dto/bundle/CreateMemberBundle.java
  src/main/java/kr/ac/hs/selab/member/dto/request/CreateMemberRequest.java
  src/main/java/kr/ac/hs/selab/member/dto/response/CreateMemberResponse.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberSwaggerController.java
Labels: fix

#31 📝 [Docs/readme-30] README 추가
  README.md
Labels: docs

#35 :sparkles: [Feature/board-34] 게시판 기능 구현
  build.gradle
  src/main/java/kr/ac/hs/selab/board/application/BoardService.java
  src/main/java/kr/ac/hs/selab/board/converter/BoardConverter.java
  src/main/java/kr/ac/hs/selab/board/domain/Board.java
  src/main/java/kr/ac/hs/selab/board/dto/BoardCreateDto.java
  src/main/java/kr/ac/hs/selab/board/dto/BoardUpdateDto.java
  src/main/java/kr/ac/hs/selab/board/dto/request/BoardRequest.java
  src/main/java/kr/ac/hs/selab/board/dto/response/BoardResponse.java
  src/main/java/kr/ac/hs/selab/board/dto/response/BoardsResponse.java
  src/main/java/kr/ac/hs/selab/board/infrastructure/BoardRepository.java
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardController.java
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardSdk.java
  src/main/java/kr/ac/hs/selab/common/domain/BaseEntity.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/utils/BoardConstants.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/test/java/kr/ac/hs/selab/board/domain/BoardTest.java
Labels: feature

#36 ♻️ [Refactor/review-33] 1차 코드 리뷰에 따른 리펙토링
  README.md
  build.gradle
  src/main/java/kr/ac/hs/selab/auth/application/UserService.java
  src/main/java/kr/ac/hs/selab/auth/converter/AuthConverter.java
  src/main/java/kr/ac/hs/selab/auth/dto/request/AuthLoginRequest.java
  src/main/java/kr/ac/hs/selab/auth/dto/response/AuthLoginResponse.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtFilter.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtSecurityConfig.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/auth/presentation/AuthController.java
  src/main/java/kr/ac/hs/selab/auth/presentation/AuthSdk.java
  src/main/java/kr/ac/hs/selab/common/config/CorsConfig.java
  src/main/java/kr/ac/hs/selab/common/config/JpaConfig.java
  src/main/java/kr/ac/hs/selab/common/config/PropertiesConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SwaggerConfig.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthController.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthSdk.java
  src/main/java/kr/ac/hs/selab/common/properties/CorsProperties.java
  src/main/java/kr/ac/hs/selab/common/properties/JwtProperties.java
  src/main/java/kr/ac/hs/selab/common/properties/SwaggerProperties.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseWrapper.java
  src/main/java/kr/ac/hs/selab/common/utils/SecurityUtils.java
  src/main/java/kr/ac/hs/selab/error/exception/BusinessException.java
  src/main/java/kr/ac/hs/selab/error/exception/common/DuplicationException.java
  src/main/java/kr/ac/hs/selab/error/exception/common/InvalidArgumentException.java
  src/main/java/kr/ac/hs/selab/error/exception/common/NonExitsException.java
  src/main/java/kr/ac/hs/selab/error/handler/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorTemplate.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/converter/MemberConverter.java
  src/main/java/kr/ac/hs/selab/member/domain/Member.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Avatar.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Email.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Name.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Nickname.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Password.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Role.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/StudentId.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Terms.java
  src/main/java/kr/ac/hs/selab/member/dto/bundle/MemberCreateBundle.java
  src/main/java/kr/ac/hs/selab/member/dto/request/CreateMemberRequest.java
  src/main/java/kr/ac/hs/selab/member/dto/request/MemberCreateRequest.java
  src/main/java/kr/ac/hs/selab/member/dto/response/CreateMemberResponse.java
  src/main/java/kr/ac/hs/selab/member/dto/response/MemberCreateResponse.java
  src/main/java/kr/ac/hs/selab/member/infrastructure/MemberRepository.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberSdk.java
  src/main/resources/banner.txt
Labels: refactor

#39 🐛 [Fix/common-38] develop 내용 수정
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardController.java
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardSdk.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
Labels: fix

#40 🔖 Release v1.0.0
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardController.java
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardSdk.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
Labels: release

#44 🚑️ [Hotfix/common-43] 미반영된 지점 수정
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/properties/CorsProperties.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseWrapper.java
  src/main/java/kr/ac/hs/selab/common/utils/SecurityUtils.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
Labels: hofix

#45 🔖 Release v1.0.0
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/properties/CorsProperties.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseWrapper.java
  src/main/java/kr/ac/hs/selab/common/utils/SecurityUtils.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
Labels: release

#48 🚑️[Hotfix/common-47] 전체적인 에러 수정
  src/main/java/kr/ac/hs/selab/board/presentaion/BoardController.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
Labels: hofix

#50 :sparkles: [Feature/post-37] 게시글 기능 구현
  src/main/java/kr/ac/hs/selab/board/application/BoardService.java
  src/main/java/kr/ac/hs/selab/board/domain/Board.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/utils/BoardConstants.java
  src/main/java/kr/ac/hs/selab/common/utils/Constants.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/domain/Post.java
  src/main/java/kr/ac/hs/selab/post/dto/PostCreateDto.java
  src/main/java/kr/ac/hs/selab/post/dto/PostUpdateDto.java
  src/main/java/kr/ac/hs/selab/post/dto/request/PostRequest.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostResponse.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostsResponse.java
  src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostSdk.java
Labels: feature

#54 🐛 [fix/member-52] Request object error
  src/main/java/kr/ac/hs/selab/auth/dto/request/AuthLoginRequest.java
  src/main/java/kr/ac/hs/selab/member/dto/request/MemberCreateRequest.java
Labels: fix

#59 🐛 [Fix/auth-24] JWT 필터링 수정
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtFilter.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
Labels: fix

#53 🐛 [fix/post-51] 게시글 버그 수정 및 리팩토링
  src/main/java/kr/ac/hs/selab/board/application/BoardService.java
  src/main/java/kr/ac/hs/selab/board/converter/BoardConverter.java
  src/main/java/kr/ac/hs/selab/board/dto/BoardCreateDto.java
  src/main/java/kr/ac/hs/selab/board/dto/request/BoardRequest.java
  src/main/java/kr/ac/hs/selab/board/dto/response/BoardsResponse.java
  src/main/java/kr/ac/hs/selab/board/facade/BoardFacade.java
  src/main/java/kr/ac/hs/selab/board/infrastructure/BoardRepository.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardController.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardSdk.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/dto/request/PostRequest.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostResponse.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostsResponse.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostSdk.java
  src/test/java/kr/ac/hs/selab/board/domain/BoardTest.java
  src/test/java/kr/ac/hs/selab/post/domain/PostTest.java
Labels: fix
