Repository selab-hs/selab-core-api, pull requests merged in 2022-03, with the labels that each got.

#107 ✅ [Test/board-83] 게시판 테스트 케이스 작성
  build.gradle
  src/main/java/kr/ac/hs/selab/board/application/BoardService.java
  src/main/java/kr/ac/hs/selab/board/converter/BoardConverter.java
  src/main/java/kr/ac/hs/selab/board/dto/request/BoardRequest.java
  src/main/java/kr/ac/hs/selab/board/facade/BoardEventListener.java
  src/main/java/kr/ac/hs/selab/board/facade/BoardFacade.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardController.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/test/java/kr/ac/hs/selab/board/application/BoardServiceTest.java
  src/test/java/kr/ac/hs/selab/board/domain/BoardTest.java
  src/test/java/kr/ac/hs/selab/board/facade/BoardFacadeTest.java
  src/test/java/kr/ac/hs/selab/board/presentation/BoardControllerTest.java
  src/test/java/kr/ac/hs/selab/common/presentation/HealthControllerTest.java
  src/test/java/kr/ac/hs/selab/post/domain/PostTest.java
Labels: test

#118 ♻️ [Refactor/common-116] FK 제거
  script/sql/DDL.sql
  src/main/java/kr/ac/hs/selab/board/facade/BoardEventListener.java
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/domain/Comment.java
  src/main/java/kr/ac/hs/selab/comment/domain/event/CommentEvent.java
  src/main/java/kr/ac/hs/selab/comment/dto/CommentFindByPostIdAndPageDto.java
  src/main/java/kr/ac/hs/selab/comment/dto/request/CommentRequest.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentFindByPostIdAndPageResponse.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentFindResponse.java
  src/main/java/kr/ac/hs/selab/comment/eventListener/CommentEventListener.java
  src/main/java/kr/ac/hs/selab/comment/facade/CommentFacade.java
  src/main/java/kr/ac/hs/selab/comment/infrastructure/CommentRepository.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentController.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentSdk.java
  src/main/java/kr/ac/hs/selab/commentLike/application/CommentLikeService.java
  src/main/java/kr/ac/hs/selab/commentLike/converter/CommentLikeConverter.java
  src/main/java/kr/ac/hs/selab/commentLike/domain/CommentLike.java
  src/main/java/kr/ac/hs/selab/commentLike/dto/CommentLikeFindDto.java
  src/main/java/kr/ac/hs/selab/commentLike/dto/response/CommentLikeFindResponse.java
  src/main/java/kr/ac/hs/selab/commentLike/facade/CommentLikeFacade.java
  src/main/java/kr/ac/hs/selab/commentLike/infrastructure/CommentLikeRepository.java
  src/main/java/kr/ac/hs/selab/commentLike/presentation/CommentLikeController.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/domain/Post.java
  src/main/java/kr/ac/hs/selab/post/dto/request/PostRequest.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostFindByBoardIdAndPageResponse.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostFindResponse.java
  src/main/java/kr/ac/hs/selab/post/facade/PostEventListener.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostSdk.java
  src/main/java/kr/ac/hs/selab/postLike/application/PostLikeService.java
  src/main/java/kr/ac/hs/selab/postLike/converter/PostLikeConverter.java
  src/main/java/kr/ac/hs/selab/postLike/domain/PostLike.java
  src/main/java/kr/ac/hs/selab/postLike/dto/PostLikeFindDto.java
  src/main/java/kr/ac/hs/selab/postLike/dto/response/PostLikeFindResponse.java
  src/main/java/kr/ac/hs/selab/postLike/facade/PostLikeFacade.java
  src/main/java/kr/ac/hs/selab/postLike/infrastructure/PostLikeRepository.java
  src/main/java/kr/ac/hs/selab/postLike/presentation/PostLikeController.java
Labels: refactor

#120 🐛 [Fix/terms-119] terms fk 삭제 및 비즈니스 로직 수정
  script/sql/DDL.sql
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/domain/Member.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Tos.java
  src/main/java/kr/ac/hs/selab/member/facade/MemberFacade.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
  src/main/java/kr/ac/hs/selab/terms/application/TermsService.java
  src/main/java/kr/ac/hs/selab/terms/domain/Terms.java
  src/main/java/kr/ac/hs/selab/terms/domain/vo/Category.java
  src/main/java/kr/ac/hs/selab/terms/infrastructure/TermsRepository.java
Labels: fix

#123 ✅ [Test/post-91] 게시글 테스트 케이스 작성
  src/main/java/kr/ac/hs/selab/post/facade/PostEventListener.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/test/java/kr/ac/hs/selab/board/application/BoardServiceTest.java
  src/test/java/kr/ac/hs/selab/board/domain/BoardTest.java
  src/test/java/kr/ac/hs/selab/board/facade/BoardEventListenerTest.java
  src/test/java/kr/ac/hs/selab/board/facade/BoardFacadeTest.java
  src/test/java/kr/ac/hs/selab/post/application/PostServiceTest.java
  src/test/java/kr/ac/hs/selab/post/domain/PostTest.java
  src/test/java/kr/ac/hs/selab/post/facade/PostEventListenerTest.java
  src/test/java/kr/ac/hs/selab/post/facade/PostFacadeTest.java
  src/test/java/kr/ac/hs/selab/post/presentation/PostControllerTest.java
Labels: test

#113 📝 [Docs/readme-112] 기능 요구사항 작성
  README.md
Labels: docs

#125 ✅ [Test/comment-92] 댓글 테스트 케이스 작성
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/facade/CommentFacade.java
  src/test/java/kr/ac/hs/selab/comment/application/CommentServiceTest.java
  src/test/java/kr/ac/hs/selab/comment/domain/CommentTest.java
  src/test/java/kr/ac/hs/selab/comment/facade/CommentFacadeTest.java
  src/test/java/kr/ac/hs/selab/comment/presentation/CommentControllerTest.java
  src/test/java/kr/ac/hs/selab/post/application/PostServiceTest.java
Labels: test

#128 ✅ [Test/postLike-93] 게시글 좋아요 테스트 케이스 작성
  src/test/java/kr/ac/hs/selab/postLike/application/PostLikeServiceTest.java
  src/test/java/kr/ac/hs/selab/postLike/facade/PostLikeFacadeTest.java
  src/test/java/kr/ac/hs/selab/postLike/presentation/PostLikeControllerTest.java
Labels: test

#129 ✅ [Test/commentLike-94] 댓글 좋아요 테스트 케이스 작성
  src/test/java/kr/ac/hs/selab/commentLike/application/CommentLikeServiceTest.java
  src/test/java/kr/ac/hs/selab/commentLike/facade/CommentLikeFacadeTest.java
  src/test/java/kr/ac/hs/selab/commentLike/presentation/CommentLikeControllerTest.java
Labels: test

#144 ✨ [Feature/notice-138] 공지사항 기능 구현
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/notice/application/NoticeService.java
  src/main/java/kr/ac/hs/selab/notice/converter/NoticeConverter.java
  src/main/java/kr/ac/hs/selab/notice/domain/Notice.java
  src/main/java/kr/ac/hs/selab/notice/dto/NoticeCreateDto.java
  src/main/java/kr/ac/hs/selab/notice/dto/NoticeFindAllByPageDto.java
  src/main/java/kr/ac/hs/selab/notice/dto/NoticeUpdateDto.java
  src/main/java/kr/ac/hs/selab/notice/dto/request/NoticeRequest.java
  src/main/java/kr/ac/hs/selab/notice/dto/response/NoticeFindAllByPageResponse.java
  src/main/java/kr/ac/hs/selab/notice/dto/response/NoticeFindResponse.java
  src/main/java/kr/ac/hs/selab/notice/dto/response/NoticeResponse.java
  src/main/java/kr/ac/hs/selab/notice/facade/NoticeFacade.java
  src/main/java/kr/ac/hs/selab/notice/infrastructure/NoticeRepository.java
  src/main/java/kr/ac/hs/selab/notice/presentation/NoticeController.java
  src/main/java/kr/ac/hs/selab/notice/presentation/NoticeSdk.java
  src/test/java/kr/ac/hs/selab/notice/application/NoticeServiceTest.java
  src/test/java/kr/ac/hs/selab/notice/domain/NoticeTest.java
  src/test/java/kr/ac/hs/selab/notice/facade/NoticeFacadeTest.java
  src/test/java/kr/ac/hs/selab/notice/presentation/NoticeControllerTest.java
Labels: feature

#154 ✨ [Feature/freePost-146] 자유게시글 기능 구현
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/free_post/application/FreePostService.java
  src/main/java/kr/ac/hs/selab/free_post/converter/FreePostConverter.java
  src/main/java/kr/ac/hs/selab/free_post/domain/FreePost.java
  src/main/java/kr/ac/hs/selab/free_post/dto/FreePostCreateDto.java
  src/main/java/kr/ac/hs/selab/free_post/dto/FreePostFindByPageDto.java
  src/main/java/kr/ac/hs/selab/free_post/dto/FreePostUpdateDto.java
  src/main/java/kr/ac/hs/selab/free_post/dto/request/FreePostRequest.java
  src/main/java/kr/ac/hs/selab/free_post/dto/response/FreePostFindByIdResponse.java
  src/main/java/kr/ac/hs/selab/free_post/dto/response/FreePostFindByPageResponse.java
  src/main/java/kr/ac/hs/selab/free_post/dto/response/FreePostResponse.java
  src/main/java/kr/ac/hs/selab/free_post/facade/FreePostFacade.java
  src/main/java/kr/ac/hs/selab/free_post/infrastructure/FreePostRepository.java
  src/main/java/kr/ac/hs/selab/free_post/presentation/FreePostController.java
  src/main/java/kr/ac/hs/selab/free_post/presentation/FreePostSdk.java
  src/test/java/kr/ac/hs/selab/free_post/application/FreePostServiceTest.java
  src/test/java/kr/ac/hs/selab/free_post/domain/FreePostTest.java
  src/test/java/kr/ac/hs/selab/free_post/facade/FreePostFacadeTest.java
  src/test/java/kr/ac/hs/selab/free_post/presentation/FreePostControllerTest.java
Labels: feature

#153 ♻️ [Refactor/notice-152] 공지사항 리팩토링
  src/main/java/kr/ac/hs/selab/notice/application/NoticeService.java
  src/main/java/kr/ac/hs/selab/notice/converter/NoticeConverter.java
  src/main/java/kr/ac/hs/selab/notice/domain/Notice.java
  src/main/java/kr/ac/hs/selab/notice/dto/NoticeCreateDto.java
  src/main/java/kr/ac/hs/selab/notice/dto/NoticeFindByPageDto.java
  src/main/java/kr/ac/hs/selab/notice/dto/NoticeUpdateDto.java
  src/main/java/kr/ac/hs/selab/notice/dto/request/NoticeRequest.java
  src/main/java/kr/ac/hs/selab/notice/dto/response/NoticeFindByIdResponse.java
  src/main/java/kr/ac/hs/selab/notice/dto/response/NoticeFindByPageResponse.java
  src/main/java/kr/ac/hs/selab/notice/facade/NoticeFacade.java
  src/main/java/kr/ac/hs/selab/notice/presentation/NoticeController.java
  src/main/java/kr/ac/hs/selab/notice/presentation/NoticeSdk.java
  src/test/java/kr/ac/hs/selab/notice/application/NoticeServiceTest.java
  src/test/java/kr/ac/hs/selab/notice/domain/NoticeTest.java
  src/test/java/kr/ac/hs/selab/notice/facade/NoticeFacadeTest.java
  src/test/java/kr/ac/hs/selab/notice/presentation/NoticeControllerTest.java
Labels: refactor

#150 ✨ [Feature/noticeComment-141] 공지사항 댓글 기능 구현
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/notice_comment/application/NoticeCommentService.java
  src/main/java/kr/ac/hs/selab/notice_comment/converter/NoticeCommentConverter.java
  src/main/java/kr/ac/hs/selab/notice_comment/domain/NoticeComment.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/NoticeCommentCreateDto.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/NoticeCommentFindByNoticeIdAndPageDto.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/NoticeCommentUpdateDto.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/request/NoticeCommentRequest.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/response/NoticeCommentFindByNoticeIdAndPageResponse.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/response/NoticeCommentFindResponse.java
  src/main/java/kr/ac/hs/selab/notice_comment/dto/response/NoticeCommentResponse.java
  src/main/java/kr/ac/hs/selab/notice_comment/facade/NoticeCommentFacade.java
  src/main/java/kr/ac/hs/selab/notice_comment/infrastructure/NoticeCommentRepository.java
  src/main/java/kr/ac/hs/selab/notice_comment/presentation/NoticeCommentController.java
  src/main/java/kr/ac/hs/selab/notice_comment/presentation/NoticeCommentSdk.java
  src/test/java/kr/ac/hs/selab/notice_comment/application/NoticeCommentServiceTest.java
  src/test/java/kr/ac/hs/selab/notice_comment/domain/NoticeCommentTest.java
  src/test/java/kr/ac/hs/selab/notice_comment/facade/NoticeCommentFacadeTest.java
  src/test/java/kr/ac/hs/selab/notice_comment/presentation/NoticeCommentControllerTest.java
Labels: feature

#155 ✨ [Feature/freePostComment-148] 자유게시글 댓글 기능 구현
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/free_post_comment/application/FreePostCommentService.java
  src/main/java/kr/ac/hs/selab/free_post_comment/converter/FreePostCommentConverter.java
  src/main/java/kr/ac/hs/selab/free_post_comment/domain/FreePostComment.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/FreePostCommentCreateDto.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/FreePostCommentFindByFreePostIdAndPageDto.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/FreePostCommentUpdateDto.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/request/FreePostCommentRequest.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/response/FreePostCommentFindByFreePostIdAndPageResponse.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/response/FreePostCommentFindResponse.java
  src/main/java/kr/ac/hs/selab/free_post_comment/dto/response/FreePostCommentResponse.java
  src/main/java/kr/ac/hs/selab/free_post_comment/facade/FreePostCommentFacade.java
  src/main/java/kr/ac/hs/selab/free_post_comment/infrastructure/FreePostCommentRepository.java
  src/main/java/kr/ac/hs/selab/free_post_comment/presentation/FreePostCommentController.java
  src/main/java/kr/ac/hs/selab/free_post_comment/presentation/FreePostCommentSdk.java
  src/test/java/kr/ac/hs/selab/free_post_comment/application/FreePostCommentServiceTest.java
  src/test/java/kr/ac/hs/selab/free_post_comment/domain/FreePostCommentTest.java
  src/test/java/kr/ac/hs/selab/free_post_comment/facade/FreePostCommentFacadeTest.java
  src/test/java/kr/ac/hs/selab/free_post_comment/presentation/FreePostCommentControllerTest.java
Labels: feature

#159 ♻️ [Refactor/common-158] 공통 코드 리펙토링
  src/main/java/kr/ac/hs/selab/common/template/SwaggerNote.java
  src/main/java/kr/ac/hs/selab/coreQa/dto/bundle/CoreQaCreateBundle.java
  src/main/java/kr/ac/hs/selab/coreQa/dto/response/CoreQaCreateResponse.java
  src/main/java/kr/ac/hs/selab/coreQa/dto/response/CoreQaReadResponse.java
  src/main/java/kr/ac/hs/selab/coreQa/facade/CoreQaFacade.java
Labels: refactor
