Repository selab-hs/selab-core-api, pull requests merged in 2022-02, with the labels that each got.

#61 ♻️ [Refactor/auth-60] JWT 분리 작업 진행
  src/main/java/kr/ac/hs/selab/auth/jwt/Jwt.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtAuthentication.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtFilter.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
Labels: refactor

#64 :sparkles: [Feature/comment-56] 댓글 기능 구현
  src/main/java/kr/ac/hs/selab/board/facade/BoardFacade.java
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/domain/Comment.java
  src/main/java/kr/ac/hs/selab/comment/dto/CommentCreateDto.java
  src/main/java/kr/ac/hs/selab/comment/dto/CommentUpdateDto.java
  src/main/java/kr/ac/hs/selab/comment/dto/request/CommentRequest.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentResponse.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentsResponse.java
  src/main/java/kr/ac/hs/selab/comment/facade/CommentFacade.java
  src/main/java/kr/ac/hs/selab/comment/infrastructure/CommentRepository.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentController.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentSdk.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
Labels: feature

#66 :sparkles: [Feature/likes-57] 좋아요 기능 구현
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/infrastructure/CommentRepository.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/likes/application/LikeService.java
  src/main/java/kr/ac/hs/selab/likes/converter/LikeConverter.java
  src/main/java/kr/ac/hs/selab/likes/domain/Likes.java
  src/main/java/kr/ac/hs/selab/likes/domain/vo/TargetType.java
  src/main/java/kr/ac/hs/selab/likes/dto/LikeCountDto.java
  src/main/java/kr/ac/hs/selab/likes/dto/LikeCreateDto.java
  src/main/java/kr/ac/hs/selab/likes/dto/response/LikeCountResponse.java
  src/main/java/kr/ac/hs/selab/likes/dto/response/LikeResponse.java
  src/main/java/kr/ac/hs/selab/likes/facade/LikeFacade.java
  src/main/java/kr/ac/hs/selab/likes/infrastructure/LikeRepository.java
  src/main/java/kr/ac/hs/selab/likes/presentation/LikeController.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
Labels: feature

#71 :sparkles: [Refactor/board-65]
  src/main/java/kr/ac/hs/selab/board/application/BoardService.java
  src/main/java/kr/ac/hs/selab/board/domain/BoardEvent.java
  src/main/java/kr/ac/hs/selab/board/event/BoardEventListener.java
  src/main/java/kr/ac/hs/selab/board/facade/BoardFacade.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardController.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardSdk.java
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/common/config/AsyncConfig.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostSdk.java
Labels: refactor

#72 ♻️ [Feature/board-67] 게시판 전체적인 문법 수정
  src/main/java/kr/ac/hs/selab/board/application/BoardService.java
  src/main/java/kr/ac/hs/selab/board/converter/BoardConverter.java
  src/main/java/kr/ac/hs/selab/board/domain/Board.java
  src/main/java/kr/ac/hs/selab/board/dto/response/BoardFindAllResponse.java
  src/main/java/kr/ac/hs/selab/board/dto/response/BoardFindResponse.java
  src/main/java/kr/ac/hs/selab/board/dto/response/BoardResponse.java
  src/main/java/kr/ac/hs/selab/board/facade/BoardFacade.java
  src/main/java/kr/ac/hs/selab/board/infrastructure/BoardRepository.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardController.java
  src/main/java/kr/ac/hs/selab/board/presentation/BoardSdk.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostResponse.java
Labels: refactor

#74 ♻️ [Refactor/post-68] 게시글 전체적인 리팩토링
  src/main/java/kr/ac/hs/selab/board/domain/event/BoardEvent.java
  src/main/java/kr/ac/hs/selab/board/eventListener/BoardEventListener.java
  src/main/java/kr/ac/hs/selab/board/facade/BoardFacade.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentResponse.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/domain/Post.java
  src/main/java/kr/ac/hs/selab/post/domain/event/PostEvent.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostFindByBoardResponse.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostFindResponse.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostResponse.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostsResponse.java
  src/main/java/kr/ac/hs/selab/post/eventListener/PostEventListener.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostSdk.java
Labels: refactor

#75 ♻️ [Refactor/comment-69] 댓글 전체적인 리팩토링
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/domain/Comment.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentFindByPostResponse.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentFindResponse.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentResponse.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentsResponse.java
  src/main/java/kr/ac/hs/selab/comment/facade/CommentFacade.java
  src/main/java/kr/ac/hs/selab/comment/infrastructure/CommentRepository.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentController.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentSdk.java
Labels: refactor

#77 🐛 [Fix/common-76] property 및 Swagger 수정
  src/main/java/kr/ac/hs/selab/auth/jwt/Jwt.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtFilter.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SwaggerConfig.java
  src/main/java/kr/ac/hs/selab/common/presentation/SwaggerController.java
  src/main/resources/application-cors.properties
  src/main/resources/application-jwt.properties
  src/main/resources/application-swagger.properties
  src/main/resources/application.properties
  src/main/resources/config/application-dev.properties
  src/main/resources/config/application-local.properties
  src/main/resources/config/application-prod.properties
  src/main/resources/sql/selab.sql
Labels: fix

#79 🐛 [Fix/auth-78] jwt 롤백 및 코드 정리
  src/main/java/kr/ac/hs/selab/auth/application/UserService.java
  src/main/java/kr/ac/hs/selab/auth/jwt/Jwt.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtAuthentication.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtFilter.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/auth/presentation/AuthController.java
  src/main/java/kr/ac/hs/selab/common/config/CorsConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseWrapper.java
  src/main/java/kr/ac/hs/selab/common/utils/SecurityUtils.java
  src/main/java/kr/ac/hs/selab/error/handler/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/member/application/MemberService.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
  src/main/resources/config/application-dev.properties
  src/main/resources/config/application-local.properties
  src/main/resources/config/application-prod.properties
  src/main/resources/sql/selab.sql
Labels: fix

#81 ♻️ [Refactor/common-80] common 수정
  src/main/java/kr/ac/hs/selab/auth/converter/AuthConverter.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtAuthentication.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtFilter.java
  src/main/java/kr/ac/hs/selab/auth/jwt/JwtTokenProvider.java
  src/main/java/kr/ac/hs/selab/auth/presentation/AuthController.java
  src/main/java/kr/ac/hs/selab/common/config/SecurityConfig.java
  src/main/java/kr/ac/hs/selab/common/config/SwaggerConfig.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthController.java
  src/main/java/kr/ac/hs/selab/common/presentation/HealthSdk.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseWrapper.java
  src/main/java/kr/ac/hs/selab/common/utils/SecurityUtils.java
  src/main/java/kr/ac/hs/selab/error/handler/GlobalExceptionHandler.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorTemplate.java
  src/main/java/kr/ac/hs/selab/member/domain/vo/Tos.java
  src/main/java/kr/ac/hs/selab/member/infrastructure/MemberRepository.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberSdk.java
  src/main/java/kr/ac/hs/selab/terms/domain/Terms.java
Labels: refactor

#82 ♻️ [Refactor/likes-70] 좋아요 기능 분리하기
  src/main/java/kr/ac/hs/selab/board/eventListener/BoardEventListener.java
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/domain/event/CommentEvent.java
  src/main/java/kr/ac/hs/selab/comment/eventListener/CommentEventListener.java
  src/main/java/kr/ac/hs/selab/comment/facade/CommentFacade.java
  src/main/java/kr/ac/hs/selab/comment/infrastructure/CommentRepository.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentController.java
  src/main/java/kr/ac/hs/selab/commentLike/application/CommentLikeService.java
  src/main/java/kr/ac/hs/selab/commentLike/converter/CommentLikeConverter.java
  src/main/java/kr/ac/hs/selab/commentLike/domain/CommentLike.java
  src/main/java/kr/ac/hs/selab/commentLike/dto/CommentLikeDto.java
  src/main/java/kr/ac/hs/selab/commentLike/dto/CommentLikeFIndDto.java
  src/main/java/kr/ac/hs/selab/commentLike/dto/response/CommentLikeFindResponse.java
  src/main/java/kr/ac/hs/selab/commentLike/dto/response/CommentLikeResponse.java
  src/main/java/kr/ac/hs/selab/commentLike/facade/CommentLikeFacade.java
  src/main/java/kr/ac/hs/selab/commentLike/infrastructure/CommentLikeRepository.java
  src/main/java/kr/ac/hs/selab/commentLike/presentation/CommentLikeController.java
  src/main/java/kr/ac/hs/selab/commentLike/presentation/CommentLikeSdk.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseMessage.java
  src/main/java/kr/ac/hs/selab/error/template/ErrorMessage.java
  src/main/java/kr/ac/hs/selab/likes/application/LikeService.java
  src/main/java/kr/ac/hs/selab/likes/converter/LikeConverter.java
  src/main/java/kr/ac/hs/selab/likes/domain/Likes.java
  src/main/java/kr/ac/hs/selab/likes/domain/vo/TargetType.java
  src/main/java/kr/ac/hs/selab/likes/dto/LikeCountDto.java
  src/main/java/kr/ac/hs/selab/likes/dto/LikeCreateDto.java
  src/main/java/kr/ac/hs/selab/likes/dto/response/LikeCountResponse.java
  src/main/java/kr/ac/hs/selab/likes/dto/response/LikeResponse.java
  src/main/java/kr/ac/hs/selab/likes/facade/LikeFacade.java
  src/main/java/kr/ac/hs/selab/likes/infrastructure/LikeRepository.java
  src/main/java/kr/ac/hs/selab/likes/presentation/LikeController.java
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/eventListener/PostEventListener.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/postLike/application/PostLikeService.java
  src/main/java/kr/ac/hs/selab/postLike/converter/PostLikeConverter.java
  src/main/java/kr/ac/hs/selab/postLike/domain/PostLike.java
  src/main/java/kr/ac/hs/selab/postLike/dto/PostLikeDto.java
  src/main/java/kr/ac/hs/selab/postLike/dto/PostLikeFIndDto.java
  src/main/java/kr/ac/hs/selab/postLike/dto/response/PostLikeFindResponse.java
  src/main/java/kr/ac/hs/selab/postLike/dto/response/PostLikeResponse.java
  src/main/java/kr/ac/hs/selab/postLike/facade/PostLikeFacade.java
  src/main/java/kr/ac/hs/selab/postLike/infrastructure/PostLikeRepository.java
  src/main/java/kr/ac/hs/selab/postLike/presentation/PostLikeController.java
  src/main/java/kr/ac/hs/selab/postLike/presentation/PostLikeSdk.java
Labels: refactor

#86 ♻️ [Refactor/common-85] 패키지 변경 작업
  script/sql/DDL.sql
  script/sql/DML.sql
  src/main/resources/sql/selab.sql
Labels: refactor

#84 ✨ [Feature/post-58] 게시글 페이지 기능 추가
  src/main/java/kr/ac/hs/selab/post/application/PostService.java
  src/main/java/kr/ac/hs/selab/post/converter/PostConverter.java
  src/main/java/kr/ac/hs/selab/post/dto/PostFindByBoardAndPageDto.java
  src/main/java/kr/ac/hs/selab/post/dto/response/PostFindByBoardAndPageResponse.java
  src/main/java/kr/ac/hs/selab/post/facade/PostFacade.java
  src/main/java/kr/ac/hs/selab/post/infrastructure/PostRepository.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostController.java
  src/main/java/kr/ac/hs/selab/post/presentation/PostSdk.java
Labels: feature

#90 📝 [Docs/Sql-89] DDL, DML 작성
  script/sql/DDL.sql
  script/sql/DML.sql
Labels: docs

#98 ♻️ [Refactor/common-97] 공통코드 수정 작업 진행~~
  src/main/java/kr/ac/hs/selab/common/template/PageResponseTemplate.java
  src/main/java/kr/ac/hs/selab/common/template/ResponseTemplate.java
  src/main/java/kr/ac/hs/selab/common/template/SwaggerNote.kt
  src/main/java/kr/ac/hs/selab/member/presentation/MemberController.java
  src/main/java/kr/ac/hs/selab/member/presentation/MemberSdk.java
Labels: refactor

#99 ✨ [Feature/comment-95] 댓글 페이지 기능 추가
  src/main/java/kr/ac/hs/selab/comment/application/CommentService.java
  src/main/java/kr/ac/hs/selab/comment/converter/CommentConverter.java
  src/main/java/kr/ac/hs/selab/comment/dto/CommentFindByPostAndPageDto.java
  src/main/java/kr/ac/hs/selab/comment/dto/response/CommentFindByPostAndPageResponse.java
  src/main/java/kr/ac/hs/selab/comment/eventListener/CommentEventListener.java
  src/main/java/kr/ac/hs/selab/comment/facade/CommentFacade.java
  src/main/java/kr/ac/hs/selab/comment/infrastructure/CommentRepository.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentController.java
  src/main/java/kr/ac/hs/selab/comment/presentation/CommentSdk.java
Labels: feature
